
CREATE FUNCTION PF.VerificarCC(@Nº_CC char(8)) RETURNS INT
AS
	BEGIN
		DECLARE @count	INT
		SELECT @count=COUNT(1) FROM PF.CLIENTE WHERE Nº_CC=@Nº_CC
		RETURN @COUNT
	END
GO


CREATE FUNCTION PF.VerificarCodigo(@Código char(9)) RETURNS INT
AS
	BEGIN
		DECLARE @count	INT
		SELECT @count=COUNT(1) FROM PF.PRODUTO WHERE Código=@Código
		RETURN @COUNT
	END
GO

select * from PF.PRODUTO

CREATE FUNCTION PF.VerificarNúmero(@Número int) RETURNS INT
AS
	BEGIN
		DECLARE @count	INT
		SELECT @count=COUNT(1) FROM PF.ENCOMENDA WHERE Número=@Número
		RETURN @COUNT
	END
GO